accent = "#00AA44"
cursor = "#00AA44"
foreground = "#0A1A0D"
background = "#ECF5EC"
selection_foreground = "#ECF5EC"
selection_background = "#00AA44"

color0 = "#0A1A0D"
color1 = "#CC0000"
color2 = "#006B2D"
color3 = "#996600"
color4 = "#1A5C99"
color5 = "#7B2D99"
color6 = "#007A66"
color7 = "#6B8074"
color8 = "#3D5044"
color9 = "#E60000"
color10 = "#008D3E"
color11 = "#CC8400"
color12 = "#2277BB"
color13 = "#9944BB"
color14 = "#009980"
color15 = "#DFF0DF"
