accent = "#00BB33"
cursor = "#00BB33"
foreground = "#0A2010"
background = "#E0F0E0"
selection_foreground = "#E0F0E0"
selection_background = "#00BB33"

color0 = "#0A2010"
color1 = "#992200"
color2 = "#006622"
color3 = "#6B8800"
color4 = "#2D6655"
color5 = "#556B44"
color6 = "#007744"
color7 = "#5A8A5A"
color8 = "#3A6A3A"
color9 = "#BB3300"
color10 = "#00BB33"
color11 = "#88AA00"
color12 = "#448877"
color13 = "#667755"
color14 = "#009955"
color15 = "#C5E5C5"
