accent = "#00FF41"
cursor = "#00FF41"
foreground = "#00CC33"
background = "#0A0A0A"
selection_foreground = "#0A0A0A"
selection_background = "#00FF41"

color0 = "#0D0D0D"
color1 = "#FF0033"
color2 = "#00FF41"
color3 = "#CCFF00"
color4 = "#0088FF"
color5 = "#9B59B6"
color6 = "#00FFCC"
color7 = "#33FF66"
color8 = "#1A3A1A"
color9 = "#FF3355"
color10 = "#00FF41"
color11 = "#E5FF00"
color12 = "#33AAFF"
color13 = "#BB77FF"
color14 = "#33FFDD"
color15 = "#BBFFBB"
