accent = "#00AA33"
cursor = "#00AA33"
foreground = "#0A1F0A"
background = "#E5F0E5"
selection_foreground = "#E5F0E5"
selection_background = "#00AA33"

color0 = "#0A1F0A"
color1 = "#AA2200"
color2 = "#006622"
color3 = "#887700"
color4 = "#336688"
color5 = "#664488"
color6 = "#007755"
color7 = "#5A7A5A"
color8 = "#3A5A3A"
color9 = "#CC2200"
color10 = "#00AA33"
color11 = "#AA7700"
color12 = "#4488AA"
color13 = "#8855AA"
color14 = "#009966"
color15 = "#D5E8D5"
